name: Linux CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    name: Build linux images.
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Docker login
      env:
        USER_NAME: ${{ secrets.USER_NAME }}  
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        docker login -u $USER_NAME -p $PASSWORD
    
    - name: Build nginx
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
      working-directory: ./nginx
      run: |
        docker build . --file Dockerfile --tag $USER_NAME/nginx:alpine
        docker push $USER_NAME/nginx:alpine
        
    - name: Build nginx with certbot
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
      working-directory: ./nginx-certbot
      run: |
        docker build . --file Dockerfile --tag $USER_NAME/nginx:certbot --tag $USER_NAME/nginx:latest
        docker push $USER_NAME/nginx:latest
        docker push $USER_NAME/nginx:certbot

    - name: Build squid
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
      working-directory: ./squid
      run: |
        docker build . --file Dockerfile --tag $USER_NAME/squid:latest
        docker push $USER_NAME/squid:latest

    - name: Build rabbitmq
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
      working-directory: ./rabbitmq
      run: |
        docker build . --file Dockerfile --tag $USER_NAME/rabbitmq:latest
        docker push $USER_NAME/rabbitmq:latest

    - name: Build dotnet core sdk
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
      working-directory: ./dotnet/core/sdk
      run: |
        docker build . --file Dockerfile --tag $USER_NAME/dnc:sdk3.0
        docker push $USER_NAME/dnc:sdk3.0

    - name: Build dotnet core runtime
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
      working-directory: ./dotnet/core/runtime
      run: |
        docker build . --file Dockerfile --tag $USER_NAME/dnc:runtime3.0
        docker push $USER_NAME/dnc:runtime3.0

    - name: Build dotnet core aspnet
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
      working-directory: ./dotnet/core/aspnet
      run: |
        docker build . --file Dockerfile --tag $USER_NAME/dnc:aspnet3.0
        docker push $USER_NAME/dnc:aspnet3.0
